### ISSUE TITLE
Not compatible with MacOS (Darwin)

### ISSUE THREAD

**Issue by cmarquezrusso** [diodonfrost/ansible-role-ohmyzsh#3]
##### SUMMARY
The role doesnt work on Mac as there is a missing file for loading the required packages. Note this need to run without sudo as required for ansible homebrew package (package)

##### STEPS TO REPRODUCE
Run the role on a mac

> ansible-playbook main.yml --ask-become-pass --tags=ohmyzsh

main.yaml
```yaml
---
- name: Configure host.
  hosts: all
  
  roles:
    - role: diodonfrost.ohmyzsh
      when: install_ohmyzsh
      tags: ['ohmyzsh']
```

###### Workaround

> Edit file: diodonfrost.ohmyzsh/tasks/setup-ohmyzsh.yml
```yaml
- name: Setup | Package requirements
  package:
    name: "{{ package_requirements[ansible_facts['os_family']] | default(default_package_requirements) }}"
    state: present
  become: false #Required to avoid running homebrew as root. It will not work otherwise
```

> vars/Darwin.yml (New file)
```yaml
default_package_requirements:
  - git
  - zsh

zsh_bin_path: /bin/zsh
```

##### EXPECTED RESULTS
ohmyzsh installed and configured

##### ACTUAL RESULTS
Ansible returns an error:
```
TASK [diodonfrost.ohmyzsh : Include OS specific variables.] ********************
fatal: [127.0.0.1]: FAILED! => changed=false
  ansible_facts: {}
  ansible_included_var_files: []
  message: |-
    Could not find or access 'Darwin.yml'
    Searched in:
            /Users/cristian.russo/mac-dev-playbook/roles/diodonfrost.ohmyzsh/vars/Darwin.yml
            /Users/cristian.russo/mac-dev-playbook/roles/diodonfrost.ohmyzsh/Darwin.yml
            /Users/cristian.russo/mac-dev-playbook/roles/diodonfrost.ohmyzsh/tasks/vars/Darwin.yml
            /Users/cristian.russo/mac-dev-playbook/roles/diodonfrost.ohmyzsh/tasks/Darwin.yml
            /Users/cristian.russo/mac-dev-playbook/vars/Darwin.yml
            /Users/cristian.russo/mac-dev-playbook/Darwin.yml on the Ansible Controller.
    If you are using a module and expect the file to exist on the remote, see the remote_src option
```

##### ENVIRONMENT
Apple M1 13.3.1 (a) 
ansible [core 2.15.2]
Python 3.11.4
